import {
    AppstoreOutlined,
    DashboardOutlined,
    HomeOutlined,
    LinkOutlined,
    TableOutlined,
    HistoryOutlined,
    LoginOutlined,
    DownOutlined,
    MenuFoldOutlined,
    MenuUnfoldOutlined,
    RollbackOutlined,
    UserOutlined,
    BellOutlined,
    PlusOutlined,
    ReloadOutlined,
    CloseOutlined,
    SettingOutlined,
    EllipsisOutlined,
    EditOutlined,
    WarningOutlined,
    HeartOutlined,
    FormOutlined,
    InfoCircleOutlined,
    SmileOutlined,
    CloseCircleOutlined,
    LeftOutlined,
    RightOutlined,
    CheckCircleOutlined,
    AppstoreAddOutlined,
    LayoutOutlined,
    DeleteOutlined,
    EyeOutlined,
    PictureOutlined,
    ZoomOutOutlined,
    ZoomInOutlined,
    FullscreenOutlined,
    UndoOutlined,
    RedoOutlined,
    RotateRightOutlined,
    RotateLeftOutlined,
    DingdingOutlined,
    LoadingOutlined,
} from '@ant-design/icons-vue'

const compList = [
    AppstoreOutlined,
    DashboardOutlined,
    HomeOutlined,
    LinkOutlined,
    TableOutlined,
    HistoryOutlined,
    LoginOutlined,
    DownOutlined,
    MenuFoldOutlined,
    MenuUnfoldOutlined,
    RollbackOutlined,
    UserOutlined,
    BellOutlined,
    PlusOutlined,
    ReloadOutlined,
    CloseOutlined,
    SettingOutlined,
    EllipsisOutlined,
    EditOutlined,
    WarningOutlined,
    HeartOutlined,
    FormOutlined,
    InfoCircleOutlined,
    SmileOutlined,
    CloseCircleOutlined,
    LeftOutlined,
    RightOutlined,
    CheckCircleOutlined,
    AppstoreAddOutlined,
    LayoutOutlined,
    DeleteOutlined,
    EyeOutlined,
    PictureOutlined,
    ZoomOutOutlined,
    ZoomInOutlined,
    FullscreenOutlined,
    UndoOutlined,
    RedoOutlined,
    RotateRightOutlined,
    RotateLeftOutlined,
    DingdingOutlined,
    LoadingOutlined,
]

export default {
    install(app) {
        compList.forEach((comp) => {
            app.component(`Icon${comp.name}`, comp)
        })
        return app
    },
}
